# Site
name: 'Sync2tech'
description: 'Sync2tech - Tech blog aggregator for AWS, DevOps, Selenium, Rest API'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'sync2tech'
email: 'contact@sync2tech.com'
mailchimp-list: '#'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sync2Tech
      site:           https://www.Sync2Tech.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Mohan, the author of Sync2Tech, the theme you're currently previewing. I hope you like it!"
      email:          contact@sync2Tech.com
      twitter:        #
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
